name: Renovate

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v36.38.0
